package hu.farcsal.cms.entity.spec;

import java.util.Locale;

/**
 * ISO 639-1 language codes.
 * @author zoli
 */
public enum LanguageCode {

    AB("Abkhaz", "аҧсуа бызшәа"),
    AA("Afar", "Afaraf"),
    AF("Afrikaans", "Afrikaans"),
    AK("Akan", "Akan"),
    SQ("Albanian", "Shqip"),
    AM("Amharic", "አማርኛ"),
    AR("Arabic", "العربية"),
    AN("Aragonese", "aragonés"),
    HY("Armenian", "Հայերեն"),
    AS("Assamese", "অসমীয়া"),
    AV("Avaric", "авар мацӀ"),
    AE("Avestan", "avesta"),
    AY("Aymara", "aymar aru"),
    AZ("Azerbaijani", "azərbaycan dili"),
    BM("Bambara", "bamanankan"),
    BA("Bashkir", "башҡорт теле"),
    EU("Basque", "euskara"),
    BE("Belarusian", "беларуская мова"),
    BN("Bengali", "বাংলা"),
    BH("Bihari", "भोजपुरी"),
    BI("Bislama", "Bislama"),
    BS("Bosnian", "bosanski jezik"),
    BR("Breton", "brezhoneg"),
    BG("Bulgarian", "български език"),
    MY("Burmese", "ဗမာစာ"),
    CA("Catalan", "català"),
    CH("Chamorro", "Chamoru"),
    CE("Chechen", "нохчийн мотт"),
    NY("Chichewa", "chiCheŵa"),
    ZH("Chinese", "中文 (Zhōngwén)"),
    CV("Chuvash", "чӑваш чӗлхи"),
    KW("Cornish", "Kernewek"),
    CO("Corsican", "corsu"),
    CR("Cree", "ᓀᐦᐃᔭᐍᐏᐣ"),
    HR("Croatian", "hrvatski jezik"),
    CS("Czech", "čeština"),
    DA("Danish", "dansk"),
    DV("Divehi", "ދިވެހި"),
    NL("Dutch", "Nederlands"),
    DZ("Dzongkha", "རྫོང་ཁ"),
    EN("English", "English"),
    EO("Esperanto", "Esperanto"),
    ET("Estonian", "eesti"),
    EE("Ewe", "Eʋegbe"),
    FO("Faroese", "føroyskt"),
    FJ("Fijian", "vosa Vakaviti"),
    FI("Finnish", "suomi"),
    FR("French", "français"),
    FF("Fula", "Fulfulde"),
    GL("Galician", "galego"),
    KA("Georgian", "ქართული"),
    DE("German", "Deutsch"),
    EL("Greek", "ελληνικά"),
    GN("Guaraní", "Avañe'ẽ"),
    GU("Gujarati", "ગુજરાતી"),
    HT("Haitian", "Kreyòl ayisyen"),
    HA("Hausa", "هَوُسَ"),
    HE("Hebrew", "עברית"),
    HZ("Herero", "Otjiherero"),
    HI("Hindi", "हिन्दी"),
    HO("Hiri Motu", "Hiri Motu"),
    HU("Hungarian", "magyar"),
    IA("Interlingua", "Interlingua"),
    ID("Indonesian", "Bahasa Indonesia"),
    IE("Interlingue", "Interlingue"),
    GA("Irish", "Gaeilge"),
    IG("Igbo", "Asụsụ Igbo"),
    IK("Inupiaq", "Iñupiaq"),
    IO("Ido", "Ido"),
    IS("Icelandic", "Íslenska"),
    IT("Italian", "italiano"),
    IU("Inuktitut", "ᐃᓄᒃᑎᑐᑦ"),
    JA("Japanese", "日本語 (にほんご)"),
    JV("Javanese", "basa Jawa"),
    KL("Kalaallisut", "kalaallisut"),
    KN("Kannada", "ಕನ್ನಡ"),
    KR("Kanuri", "Kanuri"),
    KS("Kashmiri", "कश्मीरी"),
    KK("Kazakh", "қазақ тілі"),
    KM("Khmer", "ខ្មែរ"),
    KI("Kikuyu", "Gĩkũyũ"),
    RW("Kinyarwanda", "Ikinyarwanda"),
    KY("Kyrgyz", "Кыргызча"),
    KV("Komi", "коми кыв"),
    KG("Kongo", "Kikongo"),
    KO("Korean", "한국어"),
    KU("Kurdish", "Kurdî"),
    KJ("Kwanyama", "Kuanyama"),
    LA("Latin", "latine"),
    LB("Luxembourgish", "Lëtzebuergesch"),
    LG("Ganda", "Luganda"),
    LI("Limburgish", "Limburgs"),
    LN("Lingala", "Lingála"),
    LO("Lao", "ພາສາລາວ"),
    LT("Lithuanian", "lietuvių kalba"),
    LU("Luba-Katanga", "Tshiluba"),
    LV("Latvian", "latviešu valoda"),
    GV("Manx", "Gaelg"),
    MK("Macedonian", "македонски јазик"),
    MG("Malagasy", "fiteny malagasy"),
    MS("Malay", "bahasa Melayu"),
    ML("Malayalam", "മലയാളം"),
    MT("Maltese", "Malti"),
    MI("Māori", "te reo Māori"),
    MR("Marathi (Marāṭhī)", "मराठी"),
    MH("Marshallese", "Kajin M̧ajeļ"),
    MN("Mongolian", "монгол"),
    NA("Nauru", "Ekakairũ Naoero"),
    NV("Navajo", "Diné bizaad"),
    ND("Northern Ndebele", "isiNdebele"),
    NE("Nepali", "नेपाली"),
    NG("Ndonga", "Owambo"),
    NB("Norwegian Bokmål", "Norsk bokmål"),
    NN("Norwegian Nynorsk", "Norsk nynorsk"),
    NO("Norwegian", "Norsk"),
    II("Nuosu", "ꆈꌠ꒿ Nuosuhxop"),
    NR("Southern Ndebele", "isiNdebele"),
    OC("Occitan", "occitan"),
    OJ("Ojibwe", "ᐊᓂᔑᓈᐯᒧᐎᓐ"),
    CU("Old Church Slavonic", "ѩзыкъ словѣньскъ"),
    OM("Oromo", "Afaan Oromoo"),
    OR("Oriya", "ଓଡ଼ିଆ"),
    OS("Ossetian", "ирон æвзаг"),
    PA("Panjabi", "ਪੰਜਾਬੀ"),
    PI("Pāli", "पाऴि"),
    FA("Persian (Farsi)", "فارسی"),
    PL("Polish", "język polski"),
    PS("Pashto", "پښتو"),
    PT("Portuguese", "português"),
    QU("Quechua", "Runa Simi"),
    RM("Romansh", "rumantsch grischun"),
    RN("Kirundi", "Ikirundi"),
    RO("Romanian", "limba română"),
    RU("Russian", "русский язык"),
    SA("Sanskrit (Saṁskṛta)", "संस्कृतम्"),
    SC("Sardinian", "sardu"),
    SD("Sindhi", "सिन्धी"),
    SE("Northern Sami", "Davvisámegiella"),
    SM("Samoan", "gagana fa'a Samoa"),
    SG("Sango", "yângâ tî sängö"),
    SR("Serbian", "српски језик"),
    GD("Scottish Gaelic", "Gàidhlig"),
    SN("Shona", "chiShona"),
    SI("Sinhala", "සිංහල"),
    SK("Slovak", "slovenčina"),
    SL("Slovene", "slovenski jezik"),
    SO("Somali", "Soomaaliga"),
    ST("Southern Sotho", "Sesotho"),
    ES("Spanish", "español"),
    SU("Sundanese", "Basa Sunda"),
    SW("Swahili", "Kiswahili"),
    SS("Swati", "SiSwati"),
    SV("Swedish", "Svenska"),
    TA("Tamil", "தமிழ்"),
    TE("Telugu", "తెలుగు"),
    TG("Tajik", "тоҷикӣ"),
    TH("Thai", "ไทย"),
    TI("Tigrinya", "ትግርኛ"),
    BO("Tibetan Standard", "བོད་ཡིག"),
    TK("Turkmen", "Türkmen"),
    TL("Tagalog", "Wikang Tagalog"),
    TN("Tswana", "Setswana"),
    TO("Tonga", "faka Tonga"),
    TR("Turkish", "Türkçe"),
    TS("Tsonga", "Xitsonga"),
    TT("Tatar", "татар теле"),
    TW("Twi", "Twi"),
    TY("Tahitian", "Reo Tahiti"),
    UG("Uyghur", "Uyƣurqə"),
    UK("Ukrainian", "українська мова"),
    UR("Urdu", "اردو"),
    UZ("Uzbek", "O‘zbek"),
    VE("Venda", "Tshivenḓa"),
    VI("Vietnamese", "Tiếng Việt"),
    VO("Volapük", "Volapük"),
    WA("Walloon", "walon"),
    CY("Welsh", "Cymraeg"),
    WO("Wolof", "Wollof"),
    FY("Western Frisian", "Frysk"),
    XH("Xhosa", "isiXhosa"),
    YI("Yiddish", "ייִדיש"),
    YO("Yoruba", "Yorùbá"),
    ZA("Zhuang", "Saɯ cueŋƅ"),
    ZU("Zulu", "isiZulu");

    public final String NATIVE_NAME, ENGLISH_NAME;

    private LanguageCode(String englishName, String nativeName) {
        ENGLISH_NAME = englishName;
        NATIVE_NAME = nativeName;
    }
    
    public static Locale getLocale(LanguageCode code) {
        return getLocale(null, code.name().toLowerCase());
    }
    
    public static Locale getLocale(Locale defLocale, String code) {
        if (code == null) return defLocale;
        return defLocale == null ? new Locale(code) : new Locale(code, defLocale.getCountry());
    }
    
    public static LanguageCode getLanguageCode(String code) {
        if (code != null) {
            for (LanguageCode lc : LanguageCode.values()) {
                if (code.toUpperCase().equals(lc.name())) {
                    return lc;
                }
            }
        }
        return null;
    }
    
}
